### ISSUE TITLE
Add responsive mode to freely resize the viewport

### ISSUE THREAD

**Issue by duongle26** [manojVivek/responsively-app#112]
![image](https://user-images.githubusercontent.com/28813618/82810469-cb49bd80-9eb8-11ea-941b-aa3ed12277e5.png)
In the Chrome dev tool, there is a mode that lets you freely resize your viewport

**Comment by kvnam** [comment]
@manojVivek - I'd like to give this a shot. Can you assign this to me? Thanks!
