### ISSUE TITLE
Client Side routing support

### ISSUE THREAD

**Issue by wrick17** [manojVivek/responsively-app#116]
When doing client side navigation, the whole page refreshes for all the devices.

Am I missing anything? Any way to get around this?

**Comment by duongle26** [comment]
I got the same problem.

**Comment by manojVivek** [comment]
The current URL syncing logic considers this as a URL change and sends it to all other devices to load it. 
We will have to think of a way to sync the URLs while supporting client side routing.

**Comment by duongle26** [comment]
You can have a button to disable syncing URL. Whoever works with client routing app can manually trigger this mode, and the browser will do the routing for you. This can be a temporary solution until you find an optinal one.

**Comment by manojVivek** [comment]
@pratyushok Thank you for pointing it out, it is changed now.
