### ISSUE TITLE
Add an option in the `Help` menu to list all available shortcuts. 

### ISSUE THREAD

**Issue by manojVivek** [manojVivek/responsively-app#124]
UI for inspiration - https://dribbble.com/shots/2563576-Shortcuts-popup-in-Targetprocess

**Comment by romanakash** [comment]
![Screenshot from 2020-05-30 18-33-04](https://user-images.githubusercontent.com/40427975/83335365-47227c00-a2a4-11ea-80e9-dc41d149ab2a.png)

So I got all the shortcuts programmatically buildDefaultTemplate in menu.js and displayed them in a message dialog box. Doesn't look that great and I did run into some problems aligning them properly. But is this kinda what is wanted?

**Comment by romanakash** [comment]
#147 Is the message dialog box fine or should I use a new browser window?

**Comment by romanakash** [comment]
Okay pushed a new commit which opens a frameless window when help->shortcuts is pressed.

![Screenshot from 2020-05-31 14-07-43](https://user-images.githubusercontent.com/40427975/83353317-a7b7c480-a349-11ea-834e-06b4b6c97a0d.png)

**Comment by romanakash** [comment]
Added a close button at the end

![Screenshot from 2020-05-31 15-15-09](https://user-images.githubusercontent.com/40427975/83354597-9bd00080-a351-11ea-84bb-2d830b30b3df.png)

**Comment by manojVivek** [comment]
Thank you so much for getting this implemented @romanakash. 
This will go live as part of v0.1.6 tonight.
