### ISSUE TITLE
FHD resolution doesn't work

### ISSUE THREAD

**Issue by cococov** [manojVivek/responsively-app#125]
When I select a HD resolution, this isn't added (or created) and all the devices are selected automatically.

![image](https://user-images.githubusercontent.com/19384973/82960264-f51de580-9f87-11ea-8fc5-7389fe809382.png)

![image](https://user-images.githubusercontent.com/19384973/82960385-58a81300-9f88-11ea-809a-0cea4d507461.png)

**Comment by alvin96** [comment]
I am facing the same problem too

**Comment by manojVivek** [comment]
@cococov @alvin96 The fix will go live in v0.1.6 release.
