### ISSUE TITLE
Adding new device on Mac app doesn't work

### ISSUE THREAD

**Issue by dlewand691** [manojVivek/responsively-app#132]
I'm trying to add a new device but it doesn't get added. Also, if "Activate Preview" is checked, all the inactive devices are activated and I have to drag them all out to deactivate them.

**Comment by SlmnAntnll** [comment]
I had this issue just now as well. I was trying to add a new device to with the dimensions into the device name (e.g. iPhone 5/SE 320x568) so I know at a quick glance the size of the device.

**Comment by sprabowo** [comment]
Duplicate [https://github.com/manojVivek/responsively-app/issues/125](https://github.com/manojVivek/responsively-app/issues/125) 

See updated here [https://github.com/manojVivek/responsively-app/issues/125#issuecomment-634552989](https://github.com/manojVivek/responsively-app/issues/125#issuecomment-634552989)

**Comment by manojVivek** [comment]
Closing as this issue as the fix had gone live with v0.1.6 yesterday. 

cc: @dlewand691 @SlmnAntnll
