### ISSUE TITLE
When multiple screens, hotkeys dialog does not appears where Responsively App is

### ISSUE THREAD

**Issue by jjavierdguezas** [manojVivek/responsively-app#152]
>Version: 0.1.6
Electron: 8.3.0
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Windows_NT x64 10.0.18362

**To Reproduce**
When there are multiple screens and Responsively App main window is in screen 2, if you open the hotkeys dialog it appears in screen 1.

**Expected Behavior**
The hotkeys dialog box appears in front of the main window, regardless of what screen it is.

*PS: the hotkeys dialog box can be resized but it can't be moved*

**Comment by jjavierdguezas** [comment]
cc: @romanakash 
related to #90

**Comment by manojVivek** [comment]
A related issue on Mac OSX, the window hides on blur but is not really closing. 
Steps to reproduce:
1. `Help -> Keyboard Shortcuts` and blur the window. The shortcut window will now disappear.
2. `Help -> About`, now in addition to the About window, the Shortcuts window is appearing as well. This confirms the shortcut window was not really closed when it disappeared on blur. 

This doesn't happen if the user has clicked the "Close" button on step 1.

**Comment by romanakash** [comment]
Ok I'll work on this later today

**Comment by romanakash** [comment]
So I made some changes which should theoretically fix the issues, but I don't have the necessary devices to test out the changes. Can you verify if #154 fixes the problem?

**Comment by jjavierdguezas** [comment]
> So I made some changes which should theoretically fix the issues, but I don't have the necessary devices to test out the changes. Can you verify if #154 fixes the problem?

tested on Windows_NT x64 10.0.18362 and it worked like a charm

**Comment by manojVivek** [comment]
Thanks for the fix @romanakash and verifying it @jjavierdguezas. I have Merged the PR.

**Comment by manojVivek** [comment]
This will go live tonight! 🎉
