### ISSUE TITLE
Browser extension opens the app but always in https://www.google.com/

### ISSUE THREAD

**Issue by jjavierdguezas** [manojVivek/responsively-app#155]
**ResponsivelyApp**
>Version: 0.1.6
Electron: 8.3.0
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Windows_NT x64 10.0.18362

**Google Chrome**
>Version 83.0.4103.61 (Official Build) (64-bit)

It opens the app but doesn't take the URL

![responsively](https://user-images.githubusercontent.com/13673443/83431925-681bd600-a438-11ea-87ec-0be79a5917e5.gif)

**Firefox**
>Version 76.0.1 (64-bit)

It says that I don't have the app installed (I do have it) and it still opens it, but it doesn't take the URL
![responsively2](https://user-images.githubusercontent.com/13673443/83432372-0d36ae80-a439-11ea-9799-314603b35cbb.gif)

**Comment by Nothing-Works** [comment]
@jjavierdguezas I think here there are two issues, 

1. for chrome the current URL is not been taking into account.
2. for firefox the extension detection does not work correctly.

**Comment by manojVivek** [comment]
@jjavierdguezas @Nothing-Works I'll check this out. Thanks for reporting.

**Comment by Nothing-Works** [comment]
@manojVivek yes, please do so, I will try my best.

**Comment by Nothing-Works** [comment]
@jjavierdguezas `Version 77.0.1 (64-bit)` **Firefox**, it opens the app for me. I have tried both locally load the package and download from addons store.

**Comment by manojVivek** [comment]
@Nothing-Works Are you checking it on Windows?

**Comment by Nothing-Works** [comment]
@manojVivek I did on both Windows and Mac, however, the [open-url](https://www.electronjs.org/docs/api/app#event-open-url-macos) is `macos` only feature so that's why the `url` is not been taken into account.
