### ISSUE TITLE
App automatically navigates to iframe URL if lazy loaded

### ISSUE THREAD

**Issue by mattkaye** [manojVivek/responsively-app#164]
Here's a URL to test it:
[https://hallettspoint.com](https://hallettspoint.com)

Scroll down and an iframe will spawn in the DOM (lazy loaded)

**Expected behavior:**
The iframe would remain embedded on the parent page.

**Actual behavior:**
Once the iframe source URL loads, it loads in the URL location bar, effectively leaving the page.

I've confirmed that this only seems to happen if an iframe is lazy loaded. I'm not positive if it has something to do with the particular iframe I'm loading. Can anyone else reproduce this?

**Comment by manojVivek** [comment]
Verified this is a bug, this is because of https://github.com/electron/electron/issues/6808. 

We need to check for `isMainFrame` field and ignore the `did-navigate-in-page`  event.

**Comment by mattkaye** [comment]
Awesome. This app looks amazing and I can't wait to start using it. I do work on a lot of sites with iframes so I hope this addressed in the queue soon. Great work guys!

**Comment by manojVivek** [comment]
@RomainFrancony Thank you so much! 

@mattkaye  This will go live tonight!
