### ISSUE TITLE
Fix the Addressbar style to handle really lengthy URLs better like other browsers

### ISSUE THREAD

**Issue by manojVivek** [manojVivek/responsively-app#170]
When a lengthy URL is previewed in the device the floating icons on the right side of the address bar look messed up. 

<img width="1639" alt="Screenshot 2020-06-08 at 11 08 25 PM" src="https://user-images.githubusercontent.com/1283424/84062738-72f8dc80-a9dd-11ea-9f34-592cbaa36b25.png">

It should be handle like how Chrome handles it:

<img width="1004" alt="Screenshot 2020-06-08 at 11 13 41 PM" src="https://user-images.githubusercontent.com/1283424/84062978-d420b000-a9dd-11ea-9d9f-c48fd244a838.png">

**Comment by manojVivek** [comment]
@AARYAN-MAHENDRA We have a new one #170 if you would like to take it. 🙂

**Comment by AARYAN-MAHENDRA** [comment]
Sure.Thanks a lot

**Comment by AARYAN-MAHENDRA** [comment]
![error](https://user-images.githubusercontent.com/64866670/84115925-7d9e8a80-aa4c-11ea-8fd5-3144ef2c131b.jpeg)
Can someone tell me why is error message is popping up when i am trying to start the app.
Thanks for Help

**Comment by AARYAN-MAHENDRA** [comment]
![modified](https://user-images.githubusercontent.com/64866670/84143756-be11fe80-aa74-11ea-8944-8252f7aa4ad5.png)
Is this okay?

**Comment by AARYAN-MAHENDRA** [comment]
shall i submit a PR ?

**Comment by manojVivek** [comment]
@AARYAN-MAHENDRA A quick suggestion, can you add a `text-overflow: ellipsis;` css property. So that the `...` gets added at the end to indicate the truncation? 

Ref: https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow

**Comment by AARYAN-MAHENDRA** [comment]
ok sure

**Comment by AARYAN-MAHENDRA** [comment]
Warning: Setting pre-commit script in package.json > scripts will be deprecated
Please move it to husky.hooks in package.json, a .huskyrc file, or a husky.config.js file
Or run ./node_modules/.bin/husky-upgrade for automatic update

See https://github.com/typicode/husky for usage

husky > pre-commit (node v12.16.3)
'#lint-staged' is not recognized as an internal or external command,
operable program or batch file.
husky > pre-commit hook failed (add --no-verify to bypass)

I am getting this message when trying to commit the staged file .Would you please tell me what to do.Thanks

**Comment by jjavierdguezas** [comment]
>I am getting this message when trying to commit the staged file .Would you please tell me what to do.Thanks

@AARYAN-MAHENDRA I reported this to @manojVivek and he will fix it this soon, as a workaround remove the `#` in the `"precommit": "#lint-staged",` script in `package.json` (you may need to install [lint-staged](https://www.npmjs.com/package/lint-staged) globally in your machine) or just pass `--no-verify` to all commands you use

**Comment by AARYAN-MAHENDRA** [comment]
ok i just did that.Thanks

**Comment by AARYAN-MAHENDRA** [comment]
#177

**Comment by AARYAN-MAHENDRA** [comment]
linked a pull request to close this issue. 
address bar modified #177

**Comment by manojVivek** [comment]
@AARYAN-MAHENDRA Thank you for the fix, this will go live tonight! 👍
