### ISSUE TITLE
update indicator/ check for update

### ISSUE THREAD

**Issue by Nothing-Works** [manojVivek/responsively-app#175]
![1](https://user-images.githubusercontent.com/18606648/84136814-ebc06d00-aa9f-11ea-9f1c-c294300434e3.png)
I think we should add for checking new versions just like vscode.

And when it's downloading the new version in the background, we should also show something like vsvode as well.

**Comment by jjavierdguezas** [comment]
@manojVivek  if you are ok with it, I can work on this

**Comment by manojVivek** [comment]
Of course @jjavierdguezas. Assigning it to you! :)
