### ISSUE TITLE
Autocomplete URL feature

### ISSUE THREAD

**Issue by AARYAN-MAHENDRA** [manojVivek/responsively-app#187]
Maybe we could add an autocomplete url feature.So the user just has to type the keyword lile-**(google,yahoo,bing)** and its gets auto completed to **(www.website.com)**  .Its not a major feature or something but I think it would be better to make it as easy as possible for user.
If you agree I would like to work on this issue.

**Comment by manojVivek** [comment]
@AARYAN-MAHENDRA I don't think this will be needed as users are not going to use it like a regular browser to visit sites. Also when not done right it will be annoying. Let's not do this at this point in time, maybe in the future. 

I'm closing this for now. 
Thanks for the suggestion though. 👍
