### ISSUE TITLE
Install error on Ubuntu 18.0.4 LTS

### ISSUE THREAD

**Issue by paulo-correia** [manojVivek/responsively-app#188]
Hi,

I'm trying install but get the follow error:
yarn package-linux          
yarn run v1.22.4
$ yarn build && electron-builder build --linux
$ concurrently "yarn build-main" "yarn build-renderer"
/bin/sh: 1: concurrently: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

I already installed the electron using:
sudo npm install -g electron --unsafe-perm=true --allow-root

I try install with sudo (sudo yarn package-linux) and get ame error message

A step-by-step installation tutorial is missing

Thanks,

Paulo

**Comment by manojVivek** [comment]
@paulo-correia It looks like the node dependencies are not installed correctly, did you run `yarn` command to install the dependencies? 

If not please run it as the first command before building the app.

**Comment by paulo-correia** [comment]
Installed AppImage, and OK
