### ISSUE TITLE
🐛 Scroll sync does not work when dragging the scrollbar

### ISSUE THREAD

**Issue by Kidcredo** [manojVivek/responsively-app#193]
I am using Responsively 0.2.0 on a Windows 10 and when I scroll using the scrollbar within the device the scroll sync function does not seem to be working.
![ky7XpmvqG1](https://user-images.githubusercontent.com/15522605/84746518-96a3c000-afa5-11ea-96c5-1437a667be89.gif)

**Comment by jonathanurias96** [comment]
I would like to work on this issue

**Comment by manojVivek** [comment]
@jonathanurias96 You need to figure out why the scrollbar drag is not generating the scroll event and how it is different from the normal scroll that it got missed from the sync events.

**Comment by jonathanurias96** [comment]
Got it! I will work on it.

**Comment by jonathanurias96** [comment]
I believe this PR can solve the issue #216. 
Please review.

**Comment by manojVivek** [comment]
This will go live in the v0.4.0 release.
