### ISSUE TITLE
Scrollbars do not appear consistent with the UI

### ISSUE THREAD

**Issue by Kidcredo** [manojVivek/responsively-app#194]
The scrollbar on Windows doesn't appear consistent with the overall user interface of the app. 
![image](https://user-images.githubusercontent.com/15522605/84803420-99db9200-b01f-11ea-8c6e-2f2e2b614f5d.png)

I am already working on a fix for this but i am unable to target the scrollbar within the device containers which are in a WebView which I am unable to fix at the moment.

**Comment by Kidcredo** [comment]
Just need to figure out how to load the same CSS that was merged recently to load every time the WebView for device containers is updated.

**Comment by manojVivek** [comment]
@Kidcredo I don't think we have to do that since that will interfere with the page's styles and might break something.

**Comment by Kidcredo** [comment]
Anyways i was unable to find a way to inject code

**Comment by manojVivek** [comment]
@Kidcredo CSS can be injected into `webview` using the `insertCss` api. Ref: https://www.electronjs.org/docs/api/web-contents#contentsinsertcsscss-options

But anyway, I'm closing this issue as we are good with it now. Thanks again for the work on this.  🙌
