### ISSUE TITLE
Reopen last opened address

### ISSUE THREAD

**Issue by Grafikart** [manojVivek/responsively-app#197]
I wonder if we could reopen Responsively with the last opened window (I can do the PR myself if needed). 
We would record the last address in the settings and reopen it

**Comment by manojVivek** [comment]
@Grafikart The user could set the required page as home to achieve that? 

But if we are doing this then we should have a settings in user preferences to control this behavior instead of making it the default. Let me know your thoughts.

**Comment by Grafikart** [comment]
I'm working on multiple site and i'm used to this behaviour from chrome. Ok for the new preference I'll start working on this feature this week end.
