### ISSUE TITLE
Add an option to hide the status bar

### ISSUE THREAD

**Issue by manojVivek** [manojVivek/responsively-app#198]
> Could we have an option to hide this status bar (if we are short on screen height ?)
> 
> _Originally posted by @Grafikart in https://github.com/manojVivek/responsively-app/pull/196#issuecomment-645239606_

Add a checkbox menu item `View` menu -> `Show Statusbar` to control whether the status bar should be shown/hidden.

**Comment by falecci** [comment]
I can work on this. I was thinking of creating a container for `<StatusBar />`, and having a reducer for app config.

**Comment by manojVivek** [comment]
That's great @falecci, assigning this to you.
