### ISSUE TITLE
Add `App Updater` status to the status bar

### ISSUE THREAD

**Issue by manojVivek** [manojVivek/responsively-app#199]
> Hey @manojVivek do you know you can subscribe to the `'status-changed'` event of the `AppUpdater` (like [here](https://github.com/manojVivek/responsively-app/blob/ff41bf779989ea01625c3c1bbab41f3b2d8734a8/desktop-app/app/main.dev.js#L298)) and show its status transitions in this status bar?
> 
> _Originally posted by @jjavierdguezas in https://github.com/manojVivek/responsively-app/pull/196#issuecomment-645248467_

Show the status of the `app-updater` and notify the user when there is a new update available. 
Refer to the above comment for more details.

**Comment by jjavierdguezas** [comment]
Great @manojVivek  you can assign this to me
