### ISSUE TITLE
Bad Android presentation? 

### ISSUE THREAD

**Issue by boris-design** [manojVivek/responsively-app#203]
My website looks broken in Responsively, but still looks good in Android Studio. 

<img width="2379" alt="Screen Shot 2020-06-18 at 9 32 17" src="https://user-images.githubusercontent.com/57568533/84986206-d655dd80-b146-11ea-9d2c-91511a84f447.png">

Otherwise, very impressive project, thank you!

**Comment by manojVivek** [comment]
@boris-design Thanks for reporting, we will check it out.

**Comment by esprush** [comment]
@boris-design thanks for reporting. this is fixed and will be available in the next release.

you might want to check the above site in Nexus 7 and 10.

**Comment by boris-design** [comment]
Hi Suresh,

Awesome news, yet at the moment Android devices don't work (including Nexus
7 and 10). Will wait for the next release. Thank you!

Also, is it just me or <Cmd+Shift+R> doesn't work as "Reload Ignoring
Cache" at all (no action)? <Cmd+R> works just as expected.

Cheers,
Boris

**Comment by esprush** [comment]
@boris-design works fine for me. 
can you share below information:
1) Responsively app version
2) the url you are testing

**Comment by boris-design** [comment]
Sure:

1. It's on MacOS.
Version: 0.3.0

Electron: 8.3.0

Chrome: 80.0.3987.165

Node.js: 12.13.0

V8: 8.0.426.27-electron.0

OS: Darwin x64 19.5.0


2. https://itlegal.by

**Comment by esprush** [comment]
@boris-design the versions look good. not sure what could be wrong.

does anything happen when you do cache refresh?
is it possible for you to share a screen capture of the app when you do cache refresh?

**Comment by boris-design** [comment]
Sure.
https://drive.google.com/file/d/1LrvO16XIdi8P8Qa-4o-M6oF8ylEkLp-T/view?usp=sharing


Maybe something is wrong on my end. Recently I spent some time trying to
use 3 or 4 of various Android emulators I downloaded here and there until I
settle on Android Studio.

**Comment by boris-design** [comment]
That's animated entry parts that don't work at load/scroll (yet, some
animated parts does work, i.e. CTA button at the very end). I've just
recorded a longer video to show:
https://drive.google.com/file/d/1z_EVwzjsTeCLY-UEHKRCqMCQCwH71oiv/view?usp=sharing

**Comment by esprush** [comment]
@boris-design thanks for the videos.

I see the cache refresh works from the menu. does the shortcut alone not work? 
one possibility can be shortcut is interpreted by some other open application.

regarding the scroll not working - scroll events does not trigger when the page is still loading. we are looking to fix this.

**Comment by boris-design** [comment]
No problem)

1. Yes, maybe some app catches the shortcut. Have to figure out how to fix
it. Nevermind.

2. > regarding the scroll not working - scroll events does not trigger when
the page is still loading.
I think the scrolling itself works perfectly, but some animations I created
for this page's elements in Webflow (see how the panel looks) just never
get started by Android emulator in Responsively, so the elements are never
revealed by the animation. Hence, empty black areas.

[image: image.png]

**Comment by esprush** [comment]
@boris-design version 0.4.0 has been released with the fix for broken android devices.

**Comment by boris-design** [comment]
Thank you! You're awesome, guys!

**Comment by manojVivek** [comment]
Closing this, as the other items will be taken care in #222
