### ISSUE TITLE
[Feature Suggestion] Vue DevTools support

### ISSUE THREAD

**Issue by tochoromero** [manojVivek/responsively-app#209]
It would be awesome to have the ability to install the Vue DevTools extension, it is provided as a Chrome extension so it should be possible to allow it.

Thank you

**Comment by jjavierdguezas** [comment]
If this kind of feature is possible, there are a lot of chrome extensions useful for devs, not only Vue's one..

**Comment by tochoromero** [comment]
I would think the extensions would need to be vetted before added, so adding the DevTools for the major frontend frameworks seems like a good start.

**Comment by manojVivek** [comment]
@tochoromero This is a great suggestion. 🎉  

We already use `electron-devtools-installer` package to install the react dev tools extension. It takes the chrome store extension id and installs the extension.

So we can keep this a generic option to install any extension by giving the chrome store URL/extension ID. 
This way it will be more flexible at the same time the users will have control over the extension that they want to install.

**Comment by RomainFrancony** [comment]
I can work on this if you'd like

**Comment by manojVivek** [comment]
@RomainFrancony That would be great. 🎉

More details on the functionality:
1. Add a Menu option called `Manage Extensions`.
2. Click on it can open a Popup window. This popup can have the following details:
      - A button to add new extension. This will take either a chrome store extension ID or URL and install the extension using the `electron-devtools-installer` package.
      - A list of already installed extensions
      - An option to delete an installed extension. 

So excited to see this working. Please let me know if you want to discuss the UI/UX details. We can always do it on https://gitter.im/responsively-app/. 

Shall assign it to you?
