### ISSUE TITLE
Bookmarks UX Improvement

### ISSUE THREAD

**Issue by manojVivek** [manojVivek/responsively-app#218]
Improvements:
- Make the bookmarks bar sleeker. It takes up a lot of space right now.
- Make the context menu open from the bottom not hiding the bookmark item.
- capture the title and favicon of the page and show it on the bookmarks bar.

**Comment by falecci-peya** [comment]
I could make a take on this :)

**Comment by manojVivek** [comment]
@falecci-peya Sorry, I'm already halfway through it. :)

#103 is something we need to do, if you are interested.

**Comment by falecci** [comment]
@manojVivek sorry, commented with the wrong account 😆 . Sure, no problem!
