### ISSUE TITLE
help - link to Screenshot folder or change where they store 

### ISSUE THREAD

**Issue by pedroknigge** [manojVivek/responsively-app#224]
Hi! first I have to say thanks for this tool, its amazing. After using little bit I find myself not able to find where the screenshots are. If you can add a link to the folder or let user change where they store should be great. Thanks!

**Comment by manojVivek** [comment]
@pedroknigge The screenshots are stored on your desktop folder inside `Responsively Screenshots` folder. 

Please let us know if you don't see it there.

**Comment by jjavierdguezas** [comment]
We could add a menu item like `Open Screenshots Folder` that opens it (and maybe in the future lets the user change that location)

**Comment by pedroknigge** [comment]
I could found it. The problem is when I take all screenshoot together, the app create a folder but I cannot access, give me an error. Maybe because all my files are in other disk and it's creating the folder in the old desktop location.
![image](https://user-images.githubusercontent.com/63541209/86502944-340d3b00-bd7f-11ea-8c09-91b9ee310a48.png)

**Comment by pedroknigge** [comment]
> We could add a menu item like `Open Screenshots Folder` that opens it (and maybe in the future lets the user change that location). What do you think @manojVivek ?

Should be a good add! Maybe add the option to change the default folder. Thanks!

**Comment by manojVivek** [comment]
> We could add a menu item like `Open Screenshots Folder` that opens it (and maybe in the future lets the user change that location). What do you think @manojVivek ?

@jjavierdguezas Good idea and thanks for the quick implementation!

**Comment by manojVivek** [comment]
> I could found it. The problem is when I take all screenshoot together, the app create a folder but I cannot access, give me an error. Maybe because all my files are in other disk and it's creating the folder in the old desktop location.

@pedroknigge This created the screenshot folder in the current user's desktop, maybe a folder permission issue?
