### ISSUE TITLE
Horizontal Layout issue

### ISSUE THREAD

**Issue by ardenne21** [manojVivek/responsively-app#225]
Hi guys, I have just tested the web app on my Mac and run into an issue when switching to the Horizontal Layout. 
As you can see from the screenshots below when switching to the Horizontal Layout, the left menu doesn't open ( see the double line on the left between the left menu and the main view ). In this layout, I am also unable to scroll horizontally to see all the devices. 

<img width="1440" alt="Screenshot 2020-06-25 at 11 01 23" src="https://user-images.githubusercontent.com/28379635/85690393-d10f0a80-b6d3-11ea-8027-a67511df7dbc.png">
<img width="1440" alt="Screenshot 2020-06-25 at 11 02 06" src="https://user-images.githubusercontent.com/28379635/85690409-d409fb00-b6d3-11ea-97d5-2c499ac7c93a.png">

**Comment by manojVivek** [comment]
@ardenne21 Yeah, this is a terrible bug. 
We will send a fix soon, thanks for reporting it!

**Comment by RomainFrancony** [comment]
@manojVivek I can take care of this if you'd like

**Comment by manojVivek** [comment]
@RomainFrancony That would be awesome! Assigning it to you. 🎉 
 When you make a fix, please consider testing the docked device dev tools window resizing too, as it seems related to that.

**Comment by ardenne21** [comment]
> We will send a fix soon, thanks for reporting it!

Thank you for your quick reply! 
I am just testing the app ( which is awesome by the way! ) and the bug it's not blocking for me.
