### ISSUE TITLE
Input Text does not sync up

### ISSUE THREAD

**Issue by AmitKKhanchandani** [manojVivek/responsively-app#231]
Tested with ResponsivelyApp 0.4.0 (more details in the below animation screencast)

![ResponsivelyApp Input text not syncing](https://user-images.githubusercontent.com/11069057/85940146-467b1500-b938-11ea-9bea-082090dbe710.gif)

I tried out with a simple HTML form as well, example this one: https://github.com/AmitKKhanchandani/Learn-Html-CSS-JS/blob/master/HTML/42%20Complete%20Form.html

It still didn't sync up the input text.

**Comment by esprush** [comment]
@AmitKKhanchandani the app does not sync keyboard inputs yet. Its in the roadmap. should be available along with #222

**Comment by AmitKKhanchandani** [comment]
@esprush Correct,
So closing this issue as it would get fixed.

**Comment by manojVivek** [comment]
@AmitKKhanchandani #222 went live in v.0.7.0, please update the app and then it should work. 👍

**Comment by AmitKKhanchandani** [comment]
Perfect, let me try it out :)
