### ISSUE TITLE
No horizontal scroll bar when big enough device on individual layout

### ISSUE THREAD

**Issue by jjavierdguezas** [manojVivek/responsively-app#233]
>Version: 0.5.0
Electron: 8.3.0
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Windows_NT x64 10.0.18362

When you are in individual layout and the focused device is bigger than the screen `ResponsivelyApp` should show an horizontal scroll bar (at app level)
A workaround right now is to use `Shift + mouse wheel` to scroll (at least on Windows)

![scroll bar issue](https://user-images.githubusercontent.com/13673443/86235866-678e7080-bb99-11ea-92ec-4cd5c6a5cf2d.gif)

**Comment by RomainFrancony** [comment]
@manojVivek I can take care of this one, it's a simple overflow issue with flexbox

**Comment by manojVivek** [comment]
@RomainFrancony Great!
