### ISSUE TITLE
Search Extension keyword the '*' after can't control side bar.

### ISSUE THREAD

**Issue by gtk2k** [manojVivek/responsively-app#240]
Search Extension keyword input '*' and Enter key.
After can't control side bar.

**Comment by jjavierdguezas** [comment]
>Version: 0.5.0
Electron: 8.3.0
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Windows_NT x64 10.0.18362

![extensions](https://user-images.githubusercontent.com/13673443/86375087-8c601200-bc85-11ea-99c3-795b26b1ce8c.gif)


After some clicks the error shows. [here](https://pastebin.com/RFj5nBnK) a pastebin of the JSON

cc: @manojVivek

**Comment by manojVivek** [comment]
@jjavierdguezas  Great, thanks for the triage. 

@RomainFrancony Maybe be we should add some validation on the input box?

**Comment by RomainFrancony** [comment]
@manojVivek I don't know the exact specification of Chrome Store extension's ID but it seems that they are only composed of letters, so probably a regex like `/[a-z]+/i`

**Comment by manojVivek** [comment]
Yeah, the extension id is composed of lower case alphabets.

**Comment by jjavierdguezas** [comment]
@RomainFrancony @manojVivek I could only find that they are always 32 characters long
see [here](https://support.google.com/chrome/a/answer/7532015?hl=en)
![image](https://user-images.githubusercontent.com/13673443/86389238-4f504b80-bc96-11ea-90cd-ea4238e757e6.png)

**Comment by pajaydev** [comment]
I would like to work on this if it's unassigned. Thanks.

**Comment by manojVivek** [comment]
@pajaydev Appreciate it, I'm assigning it to you. 🙌 

cc: @RomainFrancony

**Comment by manojVivek** [comment]
@pajaydev Please join us on Gitter if you have any questions along the way - https://gitter.im/responsively-app/

**Comment by pajaydev** [comment]
@manojVivek  Thank you

**Comment by pajaydev** [comment]
@manojVivek I have created a PR, kindly review
