### ISSUE TITLE
Do auto-reload the page, watching for the file changes, if a local HTML file is loaded in the browser. 

### ISSUE THREAD

**Issue by manojVivek** [manojVivek/responsively-app#245]

**Comment by manojVivek** [comment]
The fix is so neat, Thanks JJ for the quick one!

**Comment by eegrok** [comment]
this isn't working for me at all on v 1.3.0 -- I tried it on a Mac M1, as well as on Windows 11 -- just simple index.html file in both cases, make changes, don't see them.
