### ISSUE TITLE
Handle OAuth new window and target blank new tab actions.

### ISSUE THREAD

**Issue by MeStrak** [manojVivek/responsively-app#248]
Hi there, I tried out responsively-app today but have an issue with authentication.

When our app loads it connects to AWS Cognito to authenticate the user, but the page doesn’t load in Responsively-app, I think because it’s external to our site.

I tried to the same In Sizzy (a similar app) and the auth screen loaded in a popup. I then authenticated and could login.

Is there a way to enable this type of popup in responsively-app to manage cases like this? I assume that there’s a similar issue with any auth service (OAuth, etc.).

**Comment by manojVivek** [comment]
That is right, OAuth based login is a problem right now. Thanks or raising it @MeStrak, adding it to the roadmap.

**Comment by manojVivek** [comment]
@MeStrak With `v0.6.0` we shipped an update to handle new tab requests by opening a new electron window. Can you check if this issue is resolved by that? 

Also, it would be great if you could give us a sample URL to test this out.

**Comment by MeStrak** [comment]
I just tested it and it's working, thanks a lot!

The first time I tried I'm not sure if there was a bug or if the popup appeared behind the main app and I didn't see it. After that I restarted the app and the login worked as expected.

Unfortunately this is actually an internal app so I'm unable to share it. I haven't been able to find another example with the same issue.

I have an open source project I'm working on at https://www.catkin.dev/ but that uses Auth0 login which worked ok even in the last version. This must be because we're using AWS Cognito internally and redirect to another page for the login, whereas Auth0 login can be launched within a popup.

Thanks a lot for doing this so quickly, it's not just the app which is responsive :)

**Comment by manojVivek** [comment]
Glad it worked! :)

**Comment by jalejandro0211** [comment]
> Glad it worked! :)

Hi, @manojVivek  doesn't work, :( can you try this page: ([https://armand1m.github.io/react-with-firebase-auth/])

I'm using Firebase authentication with react, in my local project but with this page returns the same error:

Try to log on with google option... and the console log returns:

**Code**: "auth/popup-blocked", 
**message**: "_Unable to establish a connection with the popup. It may have been blocked by the browser._"
**or** 
"_auth/popup-blocked Unable to establish a connection with the popup. It may have been blocked by the browser._"

**Comment by manojVivek** [comment]
@jalejandro0211 Are you seeing the following message in the google signing popup? 

> Couldn't sign you in
> This browser or app may not be secure. Learn more
> 
> Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in.

If you are already login, please log out once and then try to log in. Let me know if you see this screen.

**Comment by jalejandro0211** [comment]
> @jalejandro0211 Are you seeing the following message in the google signing popup?
> 
> > Couldn't sign you in
> > This browser or app may not be secure. Learn more
> > Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in.
> 
> If you are already login, please log out once and then try to log in. Let me know if you see this screen.

Hi, I restart my PC and open your app... and returns the same error
![image](https://user-images.githubusercontent.com/54046809/87248426-00857d00-c41f-11ea-93fa-f2c92900138f.png)

**Comment by manojVivek** [comment]
@jalejandro0211 It is a compatibility issue between firebase and electron. This thread has more details: https://github.com/firebase/firebase-js-sdk/issues/2478

The firebase team replied that it doesn't support the OAuth login in electron. I don't think we will be able to do anything about it from our side. 😐

**Comment by jalejandro0211** [comment]
> @jalejandro0211 It is a compatibility issue between firebase and electron. This thread has more details: [firebase/firebase-js-sdk#2478](https://github.com/firebase/firebase-js-sdk/issues/2478)
> 
> The firebase team replied that it doesn't support the OAuth login in electron. I don't think we will be able to do anything about it from our side. 😐

ohh 😐... ok tks
