### ISSUE TITLE
chrome-extension options not working

### ISSUE THREAD

**Issue by QQBoxy** [manojVivek/responsively-app#251]
Can you support users to configure chrome-extension?

![chrome-extension](https://lh3.googleusercontent.com/ufakZQOxk1vkx8yZbpz8qwhAvSzmUlkmZWbk4A7CYv3AMI_ONzMrzLUyMv4twtKlFxReNDcQ8HSnvNYkZmc=s0?.jpg)

**Comment by jjavierdguezas** [comment]
👀
> **Note: Only DevTool extensions will work properly, other general browser extensions may not work as intended.**

Right now we are no handling extensions with UI but all contributions are welcome!
maybe [electron-extensions](https://github.com/sentialx/electron-extensions) can help

**Comment by manojVivek** [comment]
The feasibility of implementing this is very less considering the lack of support from `electron`. 
Maybe we should close this for now and re-visit at a later point in time?
