### ISSUE TITLE
How hide scroll bar of mobile devices when i use mouse?

### ISSUE THREAD

**Issue by uzprocode** [manojVivek/responsively-app#255]
<img width="1906" alt="螢幕快照 2020-07-03 下午5 21 38" src="https://user-images.githubusercontent.com/21970517/86454366-b4b54280-bd51-11ea-8010-a4538be7be9b.png">
hide scroll bar.

**Comment by manojVivek** [comment]
@uzprocode This is a good suggestion. Will add it to the roadmap. 🙌

**Comment by jzabala** [comment]
I'll like to take this one!

**Comment by manojVivek** [comment]
Awesome @jzabala. Thanks for the quick PR!

**Comment by jjavierdguezas** [comment]
>Version: 0.9.0
Electron: 9.1.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363

@manojVivek  @jzabala  maybe we need to apply css styles to all scrollbars and not only the one of the `body` 
![image](https://user-images.githubusercontent.com/13673443/88825757-3caf3080-d1c8-11ea-99df-f78c23695171.png)

![image](https://user-images.githubusercontent.com/13673443/88826332-e55d9000-d1c8-11ea-8ee0-1dfeb715344e.png)

**Comment by jzabala** [comment]
Yeah, that looks like a better solution. Thanks for pointing it out @jjavierdguezas. I can create the PR for that.
