### ISSUE TITLE
Handle anchor tags with target = blank

### ISSUE THREAD

**Issue by jjavierdguezas** [manojVivek/responsively-app#261]
>Version: 0.5.0
Electron: 8.3.0
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Windows_NT x64 10.0.18362

Right now `Responsively App` does not handle `<a/>` tags with `target="_blank"` prop so clicking on them does nothing

For example create an `index.html` with the following:
```html
<!DOCTYPE html>
<html>
<body>
<a href="https://responsively.app/" target="_blank">CLICK</a>
</body>
</html>
```
Open it with Chrome and click on the link, a new tab opens on the `Responsively App` website
Open it with `Responsively App` and click the link.... Nothing happens

I think that it should go to the website inside `Responsively App` or open it on the default browser..

**Comment by jjavierdguezas** [comment]
@manojVivek  maybe [this answer on StackOverflow](https://stackoverflow.com/a/48923751)  can help and also take into account [this issue](https://github.com/electron/electron/issues/1458)

**Comment by manojVivek** [comment]
Yes @jjavierdguezas, This is related to the #248 as well, where OAuth login flow is getting blocked. 

We should make it open one new browser window so that the user gets a feel of how the app will work in the regular browser.
