### ISSUE TITLE
Forward action does not update URL in search bar

### ISSUE THREAD

**Issue by jjavierdguezas** [manojVivek/responsively-app#264]
>Version: 0.5.0
Electron: 8.3.0
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Windows_NT x64 10.0.18362

1- Open `Responsively App` _It should open in the home URL (google.com in this case)_
2- Go to any different URL or open a file
3- Press Back button 
4- Press Forward button
The URL in the search bar should be the one in step 2 but it remains showing the one in step 1

![foward](https://user-images.githubusercontent.com/13673443/86499974-5490c180-bd8e-11ea-8eed-b439a12d2327.gif)

**Comment by manojVivek** [comment]
@esprush We missed the events when the forward action is performed?

**Comment by esprush** [comment]
thanks @jjavierdguezas. @manojVivek  yes. looks like event is not handled properly. I will check this.
