### ISSUE TITLE
Make the Address bar smarter

### ISSUE THREAD

**Issue by manojVivek** [manojVivek/responsively-app#269]
- The address bar should show suggested links from the user's previous browsing history when something is typed.
- The suggestions should be ordered based on the number of times the URL was visited previously.

**Comment by karthick3018** [comment]
hi @manojVivek  if this feature is unassigned I would love to work on this ! thanks

**Comment by manojVivek** [comment]
@karthick3018 Awesome, that will be great! Assigning it to you. 🙌 

For any UI/UX reference lets handle it same as Chrome's address bar. 

Also join us on Gitter, if you have any questions along the way - https://gitter.im/responsively-app/
