### ISSUE TITLE
Why google.com at launch

### ISSUE THREAD

**Issue by mehkera** [manojVivek/responsively-app#287]
Hello all,

i ask why puting google.com when we launch the app ? it add trafic for them (i guess they don't need it !).

Is it possible to have an example page !? 

Can we personnalize the page at start up ?

Thanks for our excellent app.

**Comment by jjavierdguezas** [comment]
I personally don't care if it is google.com but if I were to change it I would use https://responsively.app/ 😉
Also you could always set any page as Home Page and customize the his behavior

**Comment by mehkera** [comment]
Yes agree.

Thanks.
