### ISSUE TITLE
how do i integrate responsively app with my maizzle project

### ISSUE THREAD

**Issue by amanvijay96** [manojVivek/responsively-app#289]
Is there any API available for integration?

**Comment by manojVivek** [comment]
@amanvijay96 I don't know much about maizzle but from what I understand, I believe maizzle emails are HTML files. So you can load them with `File` -> `Open HTML file` option and preview them. 

Please correct me if I'm wrong.

**Comment by amanvijay96** [comment]
It's like I want to send a request to the app and get the required screenshot. So how do I do it? 
Is there an API available for integration?

**Comment by manojVivek** [comment]
No @amanvijay96, we don't have that kind of integration. For now, you need to manually load the URL and create screenshots.

**Comment by amanvijay96** [comment]
is there any API reference available for responsively?

**Comment by manojVivek** [comment]
@amanvijay96 There are no APIs as such, just a Desktop App.
