### ISSUE TITLE
Add a border to the devices based on a switch in the user preference. 

### ISSUE THREAD

**Issue by diego-vieira** [manojVivek/responsively-app#290]
Is there an option to set the background color to something other than the gray one?

One of my projects use the same hex color as the app making it hard to see the edge of each page.

Thanks

**Comment by manojVivek** [comment]
@diego-vieira We have an issue open for having a light theme for the app #238. But that is a bigger change and will take time. 

But meanwhile, we can add some kind of device border highlighting like in the below screenshot. Let us know if that will work for you. 

<img width="250" alt="Screenshot 2020-07-08 at 5 15 37 PM" src="https://user-images.githubusercontent.com/1283424/86914939-c24a3e00-c13e-11ea-981f-f7ac1ccede58.png">

**Comment by diego-vieira** [comment]
@manojVivek that'd be perfect. Very kind of you to reply so quickly. Many thanks

**Comment by diego-vieira** [comment]
@manojVivek I can do this one, but I can't see a way to assign this issue to myself?

**Comment by manojVivek** [comment]
That is awesome, I'm assigning it to you! 🙌 

You can just add a switch in the `UserPreferences` component and based on the value show a border. So that the users can selectively enable it. 

Also, you can join us here if you get any questions along the way - https://gitter.im/responsively-app/
