### ISSUE TITLE
Weird behavior when resizing Responsive Mode device

### ISSUE THREAD

**Issue by jjavierdguezas** [manojVivek/responsively-app#291]
>Version: 0.6.0
Electron: 8.3.0
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Windows_NT x64 10.0.18362

When we have the special Responsive Mode device and also other devices, when trying to resize the device it gets very hard sometimes. 
![resp](https://user-images.githubusercontent.com/13673443/86898316-d83d0c00-c108-11ea-9026-460a7076ec2c.gif)

I think this is because the special device is too close to the next one, because it seems that the resizing stop when hovering another device area. Also the mouse pointer gets too far too soon from the resizing handler so it is easy reach another device or the end on the ResponsivelyApp window

**Comment by kvnam** [comment]
Thanks @jjavierdguezas, I'll look into this and add a fix.

**Comment by manojVivek** [comment]
@kvnam Maybe we could just add some extra margins for the re-sizable devices as a quick fix. We know getting the right UX for this feature is a little too complicated.

**Comment by kvnam** [comment]
Sure @manojVivek, I'll see if I can figure out better solution, but will push the extra margins fix first though.
