### ISSUE TITLE
Add SEO tips

### ISSUE THREAD

**Issue by BraydenTW** [manojVivek/responsively-app#294]

**Comment by manojVivek** [comment]
@BraydenTW thanks for raising this, can you please add more details on what kind of SEO tips?

**Comment by BraydenTW** [comment]
Yeah no problem. I was thinking of having a dedicated section for SEO tips (Mobile friendless, meta tags, keywords). Somewhat like issue #109 but have more of an emphasis on giving SEO tips. This would be great because it would be a “one-stop-shop” for this type of metrics section.

**Comment by manojVivek** [comment]
Hm, I feel that will be a whole new project on its own. 😄 
But yeah will add it on the Roadmap.

**Comment by BraydenTW** [comment]
Oh ok 😅 I think you just gave me an idea 👍
