### ISSUE TITLE
App does not run on windows 7

### ISSUE THREAD

**Issue by chaitaliss** [manojVivek/responsively-app#298]
Downloaded and launched but it displays blank page.

See the screenshot attached.

![image](https://user-images.githubusercontent.com/30620931/87004857-bc566a80-c1db-11ea-83fb-dcde2578f0fd.png)

**Comment by jjavierdguezas** [comment]
hi @chaitaliss I couldnt reproduce it
![image](https://user-images.githubusercontent.com/13673443/87018970-51ecfc80-c1d2-11ea-9af2-450025b1bafc.png)

- Which version of Windows 7 do you have? (Win+R , type winver then hit ENTER)
- Can you share the info in the About dialog of Responsively? (press F1 inside Responsively)
- Which version of .NET Framework do you have installed (I think it should be >= .NET 4.7

I tested it in a fresh Azure VM with Windows 7, I only installed these programs
![image](https://user-images.githubusercontent.com/13673443/87019427-e48d9b80-c1d2-11ea-90de-0ddf4d8cb455.png)

**Comment by chaitaliss** [comment]
Hey, I am able to view it today, not sure why it was not working. I took long time to load screens on app then it loaded. 
As it loaded now on win 7 hence closing this ticket.
