### ISSUE TITLE
Add an option in user preference to configure screenshots location

### ISSUE THREAD

**Issue by richosr** [manojVivek/responsively-app#307]
The destination for screen shots needs to be configurable.

Writing to the protected desktop is not good practice and is flagged by Anti-Virus software as BAD!

![image](https://user-images.githubusercontent.com/992654/87240428-bc58a380-c443-11ea-8c19-53501fc9ef4a.png)

Steve

**Comment by manojVivek** [comment]
@richosr Thanks for raising this, adding it to the roadmap.
