### ISSUE TITLE
Design an image for social media preview(OG Image)

### ISSUE THREAD

**Issue by manojVivek** [manojVivek/responsively-app#312]
Need an image designed that can be used as a preview image while sharing the website URL on social media. 

I'm thinking something like this [image](https://lirp-cdn.multiscreensite.com/resource_center/dms3rep/multi/opt/og-image-960w.png) with the screenshot of the app and the logo and name on the top. But open to new ideas.

**Comment by rossmoody** [comment]
Maybe something like this?

![responsively-2](https://user-images.githubusercontent.com/29072694/87714352-7f9ced00-c760-11ea-90b1-93fa4ab5053b.png)
![responsively-1](https://user-images.githubusercontent.com/29072694/87714359-81ff4700-c760-11ea-8a0d-3c566525fb0c.png)

**Comment by manojVivek** [comment]
@rossmoody thank you so much for mocking these up. These look great! I like the second one especially.
Do you think we should make the name a little bigger?

**Comment by manojVivek** [comment]
Something like this would be great:
<img width="564" alt="Screenshot 2020-07-17 at 11 39 32 PM" src="https://user-images.githubusercontent.com/1283424/87817627-ec120c00-c886-11ea-96f4-9d63580f9d7b.png">

**Comment by rossmoody** [comment]
Yeah that looks totally incredible. I'll brb

**Comment by rossmoody** [comment]
![responsively-3](https://user-images.githubusercontent.com/29072694/87820263-9efc4e80-c822-11ea-9c0b-291a1dad7d7c.png)

I pulled the blue from the UI buttons.

**Comment by manojVivek** [comment]
This is so cool @rossmoody! 😎 Thank you so much. 
Can you also attach the source files please so that I can drop in screenshots previewing different websites?

**Comment by rossmoody** [comment]
I made this in Figma. I can invite you as an editor if you'd like. What's your email? https://www.figma.com/file/rBP9Wb7pZmUFSo3tGu5gI2/Marketing?node-id=0%3A1

**Comment by manojVivek** [comment]
Or I can add you to responsively Figma account so that all the designs are in one place if you can send your email? 
I'm fine either way, my email id is p.manoj.vivek@gmail.com

**Comment by rossmoody** [comment]
Ah, very cool! That's super rad actually, maybe there are other places I could assist.

**Comment by rossmoody** [comment]
my email is `fiftyfivehis (at) gmail .com`

**Comment by manojVivek** [comment]
@rossmoody  Done

**Comment by manojVivek** [comment]
@rossmoody Thanks so much for your help on this one. 

@all-contributors Please add @rossmoody for design.

**Comment by manojVivek** [comment]
@sebasrodriguez Please join our community on Gitter - https://gitter.im/responsively-app/, for any discussions in the future. 
Thanks again!
