### ISSUE TITLE
Zoom controls are hidden below devices tab in individual device mode

### ISSUE THREAD

**Issue by sebastianlp** [manojVivek/responsively-app#313]
When you are working with a setup like the image below (using a screen spliced by 2/3 and 1/3) and working with some devices to make the tab appears, you open the Zoom input, the submenu opens below the devices tab

Using this setup:
Version: 0.6.1
Electron: 8.3.0
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Darwin x64 19.4.0

Image
![image](https://user-images.githubusercontent.com/4922264/87494942-993a1980-c626-11ea-8671-9b851d8ff462.png)

**Comment by manojVivek** [comment]
@sebastianlp This is a terrible bug, thanks for reporting it. 👍

**Comment by pajaydev** [comment]
@manojVivek  Shall I take this one ?.

**Comment by manojVivek** [comment]
@pajaydev That would be awesome. Assigning it to you. 👍

**Comment by manojVivek** [comment]
@pajaydev @sebastianlp's PR is fixing it, you haven't looked into it. 
Closing this issue with it.
