### ISSUE TITLE
Windows Blocking Download

### ISSUE THREAD

**Issue by kaknut** [manojVivek/responsively-app#314]
Windows defender is blocking the download and app has been marked unsafe. I'll suggest the product owner @manojVivek to fill out the Microsoft feedback form.

![1](https://user-images.githubusercontent.com/33004850/87567462-edee9a80-c6e1-11ea-81ec-3a0942ae0ddb.png)
![2](https://user-images.githubusercontent.com/33004850/87567441-e9c27d00-c6e1-11ea-84d5-d605b8ca4a95.png)
![3](https://user-images.githubusercontent.com/33004850/87567459-ed560400-c6e1-11ea-9473-b09877c38ed6.png)

**Comment by AmitKKhanchandani** [comment]
#151

**Comment by manojVivek** [comment]
@kaknut This is a duplicate of #151, please watch for the updates there.  
Thanks, @AmitKKhanchandani!
