### ISSUE TITLE
0.7.0 - unable to install React Dev Tools

### ISSUE THREAD

**Issue by Nightliss** [manojVivek/responsively-app#315]
OS: Win10 x64 Pro v2004
Resposively 0.7.0

Hey there,

I just installed latest version of Responsively (first time user) and I'm unable to install React Dev Tools:
![image](https://user-images.githubusercontent.com/30467858/87637106-09898d80-c742-11ea-9b7d-fa6d4ec016a4.png)

Redux DevTools have been installed just fine.

**Comment by jjavierdguezas** [comment]
I can confirm that this is happening

**Comment by pajaydev** [comment]
@jjavierdguezas  am also able to reproduce, getting this error

```
Error occurred in handler for 'install-extension': Error: Invalid header: Does not start with Cr24
    at crxToZip (/Users/aprathap/Documents/git/responsively-app/desktop-app/node_modules/unzip-crx/dist/index.js:32:15)
    at /Users/aprathap/Documents/git/responsively-app/desktop-app/node_modules/unzip-crx/dist/index.js:57:32
```

**Comment by manojVivek** [comment]
Any reason why this is only happening for this extension? 🤔

**Comment by jjavierdguezas** [comment]
https://github.com/MarshallOfSound/electron-devtools-installer/issues/141 👀👀

**Comment by manojVivek** [comment]
@jjavierdguezas Great find! Looks like a fix went in `electron-devtools-installer v3.1.1` yesterday. I'll upgrade the version. 👍

**Comment by manojVivek** [comment]
@Nightliss This will go live in next week's release.

**Comment by tpikachu** [comment]
`Warnings loading extension at /Users/XXXXX : Unrecognized manifest key 'browser_action'. Unrecognized manifest key 'minimum_chrome_version'. Unrecognized manifest key 'update_url'. Cannot load extension with file or directory name _metadata. Filenames starting with "_" are reserved for use by the system.`

v: 3.1.1

**Comment by manojVivek** [comment]
@tpikachu These are warning because those fields in manifest are not recognized by electron, but the extension should still work fine.
