### ISSUE TITLE
UX: Remember Zoom level

### ISSUE THREAD

**Issue by geiras** [manojVivek/responsively-app#320]
**Problem**
On the screen that I usually use, both screens fit on the width if the zoom level is 70%. Every time that I close and open the app again, it resets back to 60%. 

**Solution**
Remember zoom level when the app is closed and opened again.

**Comment by manojVivek** [comment]
@geiras Great suggestion, will add it to the roadmap. 🙌

**Comment by geiras** [comment]
No problem! UI/UX designer here using the app to QA on designs. Will create more issues if I find the need for. 
Thanks for making this app possible. I would love to replace the browser as my go to tool when doing QA.

**Comment by manojVivek** [comment]
Thanks for the support and keep these coming. 🙂

**Comment by jzabala** [comment]
I would like to try this one!

**Comment by manojVivek** [comment]
@jzabala Thank you! Assigned it to you. 🙌
