### ISSUE TITLE
List `Responsively App` as an item in the native `Open With` applications list for html files

### ISSUE THREAD

**Issue by manojVivek** [manojVivek/responsively-app#330]

**Comment by jjavierdguezas** [comment]
maybe this can help
https://www.electron.build/configuration/configuration
![image](https://user-images.githubusercontent.com/13673443/87874764-d0188280-c9cc-11ea-9960-4094fc007c89.png)

```json
"build": {
  "fileAssociations": [{
    "ext": "html",
    "role": "Viewer"
  }]
}
```
