### ISSUE TITLE
UX: Address Bar suggestion keyboard interaction

### ISSUE THREAD

**Issue by manojVivek** [manojVivek/responsively-app#338]
Add the usual drop-down's keyboard interactions for the address bar suggestions:

1. `Up` and `Down` keys to highlight the items in the list
2. `Enter` key to navigate to the highlighted URL.

**Comment by manojVivek** [comment]
@karthick3018

**Comment by karthick3018** [comment]
@manojVivek  thanks !

**Comment by manojVivek** [comment]
Also, we can add `ESC` key to close the suggestions.

**Comment by karthick3018** [comment]
yeah that will be gud working on that too !

**Comment by manojVivek** [comment]
@abakermi This issue was already picked up by @karthick3018. It would have been great if you could have picked an un-assigned issue. :) 

@karthick3018 Do you mind if we go ahead with @abakermi's PR?

**Comment by karthick3018** [comment]
@manojVivek  your call manoj i've done with downshift  !

**Comment by manojVivek** [comment]
Ok @karthick3018, let's go with @abakermi's PR this time then.

You can check out the other issues that we have. :)
