### ISSUE TITLE
App is flagged as unsafe by Microsoft Defender Smartscreen

### ISSUE THREAD

**Issue by snwagbata** [manojVivek/responsively-app#340]
I tried to download the app in the new Microsoft Edge chromium browser and the Microsoft Defender SmartScreen flagged it as unsafe
https://imgur.com/a/UIVOB4E

**Comment by jjavierdguezas** [comment]
duplicated #151

**Comment by snwagbata** [comment]
@jjavierdguezas my bad, I thought the issue had to do with Microsoft edge only
