### ISSUE TITLE
Ssl certificate error when running over LAN

### ISSUE THREAD

**Issue by gergobalogh** [manojVivek/responsively-app#366]
Error 107.
ERR_SSL_PROTOCOL_ERROR.
I've disabled ssl verification in Responsively.
In chrome it works.
![image](https://user-images.githubusercontent.com/31627579/88889172-61e38380-d248-11ea-8931-27634e0077a1.png)

**Comment by manojVivek** [comment]
@gergobalogh This is happening even after the "Disable SSL Validation" is checked in the preferences section?

**Comment by gergo-balogh** [comment]
Wow that was a fast answer :+1: 
 What more info should I provide?

**Comment by gergobalogh** [comment]
Yes, as I've mentioned in my first comment. it is disabled.
![image](https://user-images.githubusercontent.com/31627579/88893565-36b06280-d24f-11ea-9f50-3e7346d48e24.png)

**Comment by manojVivek** [comment]
@gergo-balogh Looks this error case is not handled by the SSL preference. 
I'll check more and get back soon.

Meanwhile, is there a public URL with the same error that we can use to debug this?

**Comment by gergo-balogh** [comment]
No. I'm running a local react project. If it helps maybe you could connect with Anydesk?
Thank you.

**Comment by jjavierdguezas** [comment]
@gergo-balogh @gergobalogh  if you change `https://` by `http://` does it still giving you the error?

**Comment by gergo-balogh** [comment]
That resolved the issue. Thank you!

**Comment by jjavierdguezas** [comment]
I think your app does not respond to HTTPS requests (yet 😉)
