### ISSUE TITLE
Bookmarks 

### ISSUE THREAD

**Issue by manojVivek** [manojVivek/responsively-app#37]

**Comment by Grafikart** [comment]
I start working on it (using a left drawer atm)

**Comment by manojVivek** [comment]
Thanks and exciting to know that! I'm assigning this to you. 🎉 

@Grafikart One quick design suggestion. Can you please implement the bookmarks to be shown in the space below the address bar? 

As that is how most browsers do and I think, we should keep it that way. So that, it will be more intuitive for the users than adding it to the sidebar. 

What do you think?

**Comment by Grafikart** [comment]
This is my current idea ![](https://imgur.com/SUIDPxf.png)

**Comment by manojVivek** [comment]
@Grafikart We don't have to exactly mirror the chrome user experience. But only the placement if we could do it below the address bar it would be great. The code change should be almost similar, instead of adding it to the sidebar, you will have to add it to the [NavigationControls](https://github.com/manojVivek/responsively-app/blob/master/desktop-app/app/components/NavigationControls/index.js) component.

Something like:
![bookmarks-ui](https://user-images.githubusercontent.com/1283424/83790232-79254b00-a6b5-11ea-8434-77e6bc41b946.png)

**Comment by Grafikart** [comment]
Ok do you think we should ask the user for a title or use the domain name for the bookmark ?

**Comment by manojVivek** [comment]
To start with I would suggest, we can just take the page title from <title
/> tag and use it.
If the title is missing we can fallback to the domain name.
