### ISSUE TITLE
Create a browser extension to open the app from the browser with the current page URL

### ISSUE THREAD

**Issue by manojVivek** [manojVivek/responsively-app#78]

**Comment by makampos** [comment]
Well works great on localhost but  I'am try  run this app on Microsoft Visual Studio using an option call "Browser With" and didn't work.

Its possible to run this app and make him open one adress with Default option ? Like a local host?

**Comment by manojVivek** [comment]
@makampos Did you try the "Set a Homepage" option in the address to make the required address a homepage. So that when you open the app, that address will be loaded by default. 
<img width="158" alt="Screenshot 2020-05-19 at 10 53 16 PM" src="https://user-images.githubusercontent.com/1283424/82358177-c651bd80-9a23-11ea-8f5a-64a7de1414b8.png">

**Comment by fostira** [comment]
@manojVivek This needs to get updated... The extensions are not working properly anymore...
