### ISSUE TITLE
Create a way to have a synchronized input

### ISSUE THREAD

**Issue by emmanguiang** [manojVivek/responsively-app#80]
I tried using the app on our development site, but as soon as I get to our login page and text inputs are needed I have to do it for every browser.

It would be good to have a synchronized text input.

**Comment by emmanguiang** [comment]
Never mind this, tried it on google.com and it is working properly

**Comment by atilacamurca** [comment]
Are there any configuration to make this work? I'm still not getting synchronized text input.

I'm using the Linux AppImage version 0.1.6

**Comment by AmitKKhanchandani** [comment]
@emmanguiang Can you tell me, how you able to sync the input text?, are there any specific instructions? 

Reopening this thread, 

Tested with ResponsivelyApp 0.4.0 (more details in the below animation screencast)
![ResponsivelyApp Input text not syncing](https://user-images.githubusercontent.com/11069057/85940146-467b1500-b938-11ea-9bea-082090dbe710.gif)

I tried out with a simple HTML form as well, this one: https://github.com/AmitKKhanchandani/Learn-Html-CSS-JS/blob/master/HTML/42%20Complete%20Form.html

It still didn't sync up the input text.

**Comment by manojVivek** [comment]
@AmitKKhanchandani Syncing of input field is not supported yet. It is will be taken care of in #222. Please watch out there for updates.
