### ISSUE TITLE
CTRL + R not working on other applications if resposnively is opened

### ISSUE THREAD

**Issue by SampathParavasthu** [manojVivek/responsively-app#83]
If responsively is opened and not a active window, CTRL + R does not work on other active applications. 
Had my bash opened and was trying reverse search using CTRL + R. Reverse search was not triggered, On closing responsively, it worked. Looks like reloading in this issue is causing the issue

**Comment by manojVivek** [comment]
@SampathParavasthu Yeah, I can see this happening in the latest release. 
We will add a fix for it in the next release. Thanks for reporting it. :)

**Comment by adamJLev** [comment]
Yes just figured out what was causing this (repsonsively), was going a little bit crazy lol.

**Comment by manojVivek** [comment]
@SampathParavasthu @adamJLev The fix for this went live in v.0.1.4 yesterday, hope you are finding it good.
