### ISSUE TITLE
Please add a license to this repo

### ISSUE THREAD

**Issue by mbrukman** [manojVivek/responsively-app#85]
First, thank you for sharing this project with us!

Could you please add an explicit `LICENSE` file to the repo so that it's clear
under what terms the content is provided, and under what terms user
contributions are licensed?

Per [GitHub docs on licensing][github-docs-licensing]:

> [...] without a license, the default copyright laws apply, meaning that you
> retain all rights to your source code and no one may reproduce, distribute,
> or create derivative works from your work. If you're creating an open source
> project, we strongly encourage you to include an open source license.

Thanks!

[github-docs-licensing]: https://help.github.com/articles/licensing-a-repository/#choosing-the-right-license

**Comment by manojVivek** [comment]
@mbrukman Thanks for bringing it to our notice. We have added a GNU GPLv3 license.

**Comment by mbrukman** [comment]
Thanks, @manojVivek! Just to clarify, you said:

> We have added a GNU GPLv3 license.

but the [actual license in the repo][license] is **AGPL** which is significantly differs from GPL. Which license did you intend to use here?

[license]: https://github.com/manojVivek/responsively-app/blob/230dab8667fd68547f1f9bf3019e1152ac81ea31/LICENSE

**Comment by manojVivek** [comment]
@mbrukman Yeah, that is the intended one. Sorry I sent the wrong one in the comment. :)
