### ISSUE TITLE
Local certificates

### ISSUE THREAD

**Issue by ahopkins** [manojVivek/responsively-app#87]
How can I get to settings to be able to disable certificate verification for local certs?

![image](https://user-images.githubusercontent.com/166269/82527244-9d721b00-9b3e-11ea-913f-6b2b3d4ee442.png)

**Comment by manojVivek** [comment]
@ahopkins Thanks for notifying about this, we will add a way to do this in the next release.

**Comment by ahopkins** [comment]
Awesome. And thanks for your effort on this. Looks like it will be a super helpful tool!

**Comment by manojVivek** [comment]
Added an option to selectively disable SSL validation and it went live in v0.1.4.

Screenshot:
<img width="361" alt="Screenshot 2020-05-21 at 11 36 07 PM" src="https://user-images.githubusercontent.com/1283424/82590826-f8962300-9bbb-11ea-9b7e-898764353975.png">
cc: @ahopkins

**Comment by ahopkins** [comment]
Wow, super impressed with that turn around. Thanks, looking forward to trying this out now.
