### ISSUE TITLE
Suggestion to add hotkeys

### ISSUE THREAD

**Issue by Zerstoren-ak** [manojVivek/responsively-app#90]
Hello there, first of all – thank You for the app, it's so good)

I just wanted to suggest to add those kind's of keyboard hotkeys and shortcuts, which we all are used to, like: Opt + Command + I for "Inspect Element"; "Zoom in/out" with Command + +/-;  etc.

Thank You.

**Comment by manojVivek** [comment]
@Zerstoren93  Great suggestion, will incorporate these in the future release.

**Comment by Zerstoren93** [comment]
Thank's for response)

Also, there is one more cool feature You can add to your app to realise not only devise simulation but cross-browsing as well, may be you have seen it - playwrigth: https://github.com/microsoft/playwright. Check it out, it could be very useful.

**Comment by drbyte** [comment]
Adding `CMD+L` for editing the URL would be useful too.

**Comment by romanakash** [comment]
Can I work on this?

**Comment by manojVivek** [comment]
@romanakash I think @jjavierdguezas is already working on it. You can take a look at #31 if you can. 

Thank you much for checking about it. 🙂

**Comment by jjavierdguezas** [comment]
yes @romanakash  I'm working on this, please @manojVivek  assign me this issue

**Comment by jjavierdguezas** [comment]
@manojVivek  since #171  is merged I think this issue can be closed

**Comment by manojVivek** [comment]
@jjavierdguezas Thanks, closing it. This will go live tonight. 👍
