### ISSUE TITLE
[BUG] Globally disables CTRL+R shortcut on ubuntu

### ISSUE THREAD

**Issue by elderapo** [manojVivek/responsively-app#93]
When an instance of `responsively-app` is running it's no longer possible to use `ctrl+r` shortcut for other applications. Is it a bug or intended behavior?

**Comment by manojVivek** [comment]
This is a duplicate of #83 and the fix went live on v0.1.4 yesterday.

**Comment by elderapo** [comment]
@manojVivek Now `ctrl+r` doesn't refresh `responsively-app` if it isn't focused (at least not on `ubuntu 20.04`).

**Comment by manojVivek** [comment]
@elderapo Sorry, that is the expected behavior right?

**Comment by elderapo** [comment]
Ideally `ctrl+r` should trigger `responsively-app` reload and at the same time work just fine for other applications. In other words, it could be intercepted by `responsively-app` but also should be forwarded to the currently focused application.

**Comment by manojVivek** [comment]
@elderapo I don't think that is the right behavior. The current one matches how browsers like Chrome and Firefox handle this.
