### ISSUE TITLE
update the app within the app?

### ISSUE THREAD

**Issue by Nothing-Works** [manojVivek/responsively-app#94]
Can I update the app within the app atm? I think I can not.

I think it's nice to have it.

**Comment by manojVivek** [comment]
@Nothing-Works The app is already set to update in the background whenever they is a new version released and use that on the next app launch. 

Can you check the version after re-launching it? 
Also, can you let us know the OS details you are on, if the version didn't get updated after a re-launch?

**Comment by duongle26** [comment]
I can confirm that the new version is automatically updated in the background.
