### ISSUE TITLE
Threat identified on Windows 10

### ISSUE THREAD

**Issue by Darkensses** [manojVivek/responsively-app#96]
I downloaded the release `ResponsivelyApp-Setup-0.1.4.exe` and when I executed the app, Windows Defender triggered an action. I'm sure that your project is not a 'malware' or something like that, but I think is important make a patch for this issue.

![image](https://user-images.githubusercontent.com/23271049/82638022-934a2e00-9bcb-11ea-80c2-a5f37a42817a.png)

**Comment by manojVivek** [comment]
@Darkensses Is it possible for you to attach a screenshot after changing the language to english?

**Comment by LOHT03** [comment]
I also just downloaded the latest release and tried to install it. Windows 10 (1909) Security detects it as a threat.
![image](https://user-images.githubusercontent.com/48422312/82654930-c5f43500-9c64-11ea-900c-7dffab17cc03.png)

**Comment by Darkensses** [comment]
@manojVivek please see the attached file from @LOHT03 comment. Thanks for the screenshot LOHT03 🙏

**Comment by webian** [comment]
Virus detected also downloading with Chrome
![image](https://user-images.githubusercontent.com/462601/82729093-f2f02880-9cf4-11ea-9f0f-71727534570e.png)

**Comment by avimar** [comment]
Also Happened to me today when using chrome on windows 10

Trojan:Win32/Fuery.C!cl

Downloaded the windows 10 latest release

**Comment by speckz** [comment]
I was going to post about how Trojan:Win32/Fuery.C!cl was detected with Windows Defender in ResponsivelyApp-Setup-0.1.4.exe, but looking at https://www.virustotal.com/gui/url/56599bcdd55ef9229083d438fde9978f320a0db755f9a70b04dc3d4b4eb80495/detection, it seems to be clean.

**Comment by breakstring** [comment]
Same issue, please refer to the attached image(but with Chinese UI).

![image](https://user-images.githubusercontent.com/14105911/82777235-201d1200-9e80-11ea-921d-b56c5019b1a5.png)

**Comment by manojVivek** [comment]
This looks a false positive reported for electron apps built with a specific version of `electron-builder`. We will be upgrading the version in the next release, that should fix it.

**Comment by Tiberriver256** [comment]
If anyone else just wants to try this out like me. 0.1.3 seems to download and run just fine. Thanks for the app guys this is 🔥

**Comment by speckz** [comment]
> If anyone else just wants to try this out like me. 0.1.3 seems to download and run just fine. Thanks for the app guys this is 🔥

Yes, Windows Defender does not report anything for ResponsivelyApp-Setup-0.1.3.exe. Same with https://www.virustotal.com/gui/url/c01cd26b15511c49858a3965f5c6c3b805cf03c19740ab815f63bff5c4517f2c/detection.

**Comment by kdawg1406** [comment]
Same here when downloading from the below link; Chrome detected a virus.  

https://github.com/manojVivek/responsively-app/releases/download/v0.1.4/ResponsivelyApp-Setup-0.1.4.exe

**Comment by alvaromashiro** [comment]
With Firefox in windows also detected as a virus

**Comment by manojVivek** [comment]
@Darkensses A possible fix went in with v0.1.5. Can you check if it works for you? 

https://github.com/manojVivek/responsively-app/releases

**Comment by kdawg1406** [comment]
@manojVivek I'm seeing this warning, but if I dismiss, it downloads.

![2020-05-25_14-06-43](https://user-images.githubusercontent.com/5623887/82835088-ffa98380-9e90-11ea-854f-2ab1e2646a5e.png)

**Comment by kdawg1406** [comment]
@manojVivek Windows is not happy now.  Can't install.

![2020-05-25_14-08-18](https://user-images.githubusercontent.com/5623887/82835167-38e1f380-9e91-11ea-9173-27545884f531.png)

**Comment by kdawg1406** [comment]
@manojVivek bizarre, after downloading again, Windows allowed the installer to run.  The program runs fine now.  Best to you, Karl

**Comment by manojVivek** [comment]
@kdawg1406 This warning is because the app is not signed with a certificate. But you can proceed after clicking on "More info". This is not related to the thread reported in this issue. 

Signing a Windows app needs certificates to be purchased and since that is not affordable at this state, we haven't done that. 🙂

**Comment by DanWahlin** [comment]
Thanks for the quick update @manojVivek! Such a cool app concept.

**Comment by kdawg1406** [comment]
@manojVivek this is the best app!  WOW, great idea, and programming.  Thank you!

**Comment by alvaromashiro** [comment]
> 
> 
> @Darkensses A possible fix went in with v0.1.5. Can you check if it works for you?
> 
> https://github.com/manojVivek/responsively-app/releases

New version worked in windows. No more problems with windows defender when try to download.

**Comment by Darkensses** [comment]
Hey @manojVivek after reading all the above comments, I confirmed that windows doesn't recognized it as a threat. I cax execute the app with no problems.

I close the issue. Thanks y'all for the support and comments 🥰

![image](https://user-images.githubusercontent.com/23271049/82837226-0d113e80-9e8e-11ea-81ae-b5a820c33c0c.png)

**Comment by Darkensses** [comment]
> @kdawg1406 This warning is because the app is not signed with a certificate. But you can proceed after clicking on "More info". This is not related to the thread reported in this issue.
> 
> Signing a Windows app needs purchasing of certificates from certificate providers and since that is not affordable at the current moment, we haven't done that. 🙂

I think you need to put all this info in the README, just a sugerence ✌

**Comment by jsiesquen** [comment]
Is a false positive also? what happen friends?

![image](https://user-images.githubusercontent.com/1072258/82864035-34492980-9ee9-11ea-8a37-080d90e7d987.png)

**Comment by Darkensses** [comment]
@jsiesquen please describe the steps to get this warning window and tell us what antivirus are you using. 
Also, see the comments above, it's probably a false-positive

**Comment by blizzers01** [comment]
With windows 11 I get this warning that windows defender protected me from this file 

the warning says the following: Windows protected your PC
Microsoft Defender SmartScreen prevented an unknown application from starting. Running this application may pose a risk to your PC.
i use malwarebytes antivirus, 
Can I install it anyway or not?

this is the translation of the screenshot.

if something is not understood in this comment is because I am using a translator because I do not speak or write in English.

![Captura de pantalla 2023-05-26 204503](https://github.com/responsively-org/responsively-app/assets/129692541/c63cf5a7-0cdd-4580-9bae-8bde8f28937c)
