### ISSUE TITLE
Reload CSS without reloading the page itself

### ISSUE THREAD

**Issue by JoeyJanson** [manojVivek/responsively-app#99]
First of all: this app is a must have for web development. Great work!

In Chrome I've got an extension called: CSS Reloader. This extension "will allow developers to reload CSS without reloading the page itself." I can set a hotkey (^(control) + R in my case for Mac) and the CSS will be retrieved and reloaded again without reloading the full page. This is way faster for me in a lot of cases then reloading the whole page. Is there a way to create this kind of feature for responsively? Would be great! 

Quick search; I guess this is the git repo for the extension: https://github.com/auchenberg/css-reloader

**Comment by manojVivek** [comment]
@JoeyJanson That is a great suggestion, we will look incorporating it in the next release.
